config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'
  get 'pages/about'

  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :activities

  get 'signup', to: 'members#new'
  resources :members, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
  

end

app/models/activity.rb
class Activity < ActiveRecord::Base

  belongs_to :member
  has_many :activity_categories
  has_many :categories, through: :activity_categories
  validates :location, presence: true, length: { minimum: 3, maximum: 30}
  validates :bio, presence: true, length: { minimum: 10, maximum: 940}
  validates :member_id, presence: true
end

app/models/activity_category.rb
class ActivityCategory < ActiveRecord::Base
 belongs_to :activity
 belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :activity_categories
  has_many :activities, through: :activity_categories
  
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :activities, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true, 
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i


  validates :email, presence: true, length: { maximum: 105},
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }

  has_secure_password


end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:edit, :show ,:update ,:destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @activities = Activity.paginate(page: params[:page], per_page: 5)
  end


  def new
    @activity = Activity.new
  end

  def show
   
  end

  def edit
    
  end

  def create
     @activity = Activity.new(activity_params)
     @activity.member = current_member
     if @activity.save
       flash[:success] = "Activity was successfully created"
       redirect_to activity_path(@activity)
     else
       render 'new'
     end
  end

  def update
    if @activity.update(activity_params)
      flash[:success] = "Activity was successfully updated"
      redirect_to activity_path(@activity)
    else
      render 'edit'
    end
  end

  def destroy
    @activity.destroy
    flash[:danger] = "Activity was successfully deleted"
    redirect_to activities_path
  end

  private 

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:location, :bio, category_ids: [])
  end

  def require_same_user
    if current_member != @activity.member and !current_member.admin?
      flash[:danger] = "You can only edit or delete yout own activities"
      redirect_to root_path
    end
  end

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_member, :logged_in?


  def current_member
    @current_member ||= Member.find(session[:member_id]) if session[:member_id]
  end

  def logged_in?
    !!current_member
  end


  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_activities = @category.activities.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    else
      render "edit"
    end
  end


  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? and !current_member.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @members = Member.paginate(page: params[:page], per_page: 3)
  end
 
  def new
    @member = Member.new
  end

  def edit
  end

  def update
    if @member.update(member_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to activities_path
    else
      render 'edit'
    end
  end

  def show
    @member_activities = @member.activities.paginate(page: params[:page], per_page: 5)
  end

  def create
    @member = Member.new(member_params)
    if @member.save
      session[:member_id] = @member.id
      flash[:success] = "Welecom to Gym Buddies #{@member.username}"
      redirect_to member_path(@member)
    else
      render 'new'
    end
  end

    def destroy
      @member = Member.find(params[:id])
      @member.destroy
      flash[:danger] = "User & all activities created by user have been deleted"
      redirect_to members_path
    end


  private

  def set_user
      @member = Member.find(params[:id])
  end

  def member_params
      params.require(:member).permit(:username, :email, :password)
  end

  def require_same_user
    if current_member != @member and !current_member.admin?
      flash[:danger] = "You can only edit your won account"
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? and !current_member.admin?
      flash[:danger] = "only admin users can perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to activities_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 

  def new

  end

  def create
    member = Member.find_by(email: params[:session][:email].downcase)
    if member && member.authenticate(params[:session][:password])
       session[:member_id] = member.id
       flash[:success] = "You have successfully logged in"
       redirect_to member_path(member)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:member_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(member, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(member.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: member.username, class: "img-circle")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/activities/_activity.html.erb
<% obj.each do |activity| %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">
      <div class="activity-location">
       <h4> Location: <%= activity.location %></h4>
      </div>
      <div class="activity-bio">
       <h3> Bio: <%= link_to activity.bio , activity_path(activity) %> </h3>
       <div class="activity-meta-details">
         <h4>Created by: <%= activity.member.username if activity.member %>,
                          <%= time_ago_in_words(activity.created_at) %> ago
                          last updated: <%= time_ago_in_words(activity.updated_at) %> ago</h4>
       </div>
      </div>
      <% if activity.categories.any? %>
      <h2>Activities: <%= render activity.categories %></h2>
      <% if logged_in? && (current_member == activity.member || current_member.admin?) %>
      <% end %>
        <div class="activity-actions">
          <%= link_to 'Edit', edit_activity_path(activity), class: "btn btn-primary" %>
          <%= link_to 'Delete', activity_path(activity), method: :delete, data: {confirm: "Are you sure" }, class: "btn btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
 </div>
<% end %>

app/views/activities/_form.html.erb
<%= render 'shared/errors', obj: @activity %>

  <div class="row">
    <div class="col-xs-12">
      <%= form_for(@activity, :html => {class: "form-horizontal", role: "form"}) do |f| %>
       <div class="form-group">
         <div class="control-label col-sm-4">
            <%= f.label :location %><br>
        </div>
        <div class="col-sm-3">
         <%= f.text_field :location, class: "form-control", placeholder: "Your Location e.g Manchester", autofocus: true  %>
        </div>
      </div>
        <div class="form-group">
         <div class="control-label col-sm-4">
            <%= f.label :bio %>
         </div>
         <div class="col-sm-4">
          <%= f.text_area :bio, rows: 3,  class: "form-control", placeholder: "Add you bio" %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-4 col-sm-8">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
              <% end %>
          </div>
        </div>
      </div>



      <div class="form-group">
        <div class="col-sm-offset-4 col-sm-8">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>

    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
    [<%= link_to "Cancel request and return to the activites listing", activities_path %>]
    </div>
  </div>

app/views/activities/edit.html.erb
<div class="panel panel-success">
  <div class="panel-heading">
    <div class="panel-title">
    <h3 align="center">Edit Existing Activities info</h3>
    </div>
  </div>
</div>

  <%= render 'form' %>

app/views/activities/index.html.erb
<div class="panel panel-success">
  <div class="panel-heading">
    <div class="panel-title">
    <h3 align="center">Listing All Activites</h3>
    </div>
  </div>
</div>

  <div align="center">
    <%= will_paginate %>
  </div>


<%= render 'activity', obj: @activities  %>

  <div align="center">
    <%= will_paginate %>
  </div>

app/views/activities/new.html.erb
<div class="panel panel-success">
  <div class="panel-heading">
    <div class="panel-title">
    <h3 align="center">Create a new activity</h3>
    </div>
  </div>
</div>

  <%= render 'form' %>

app/views/activities/show.html.erb
<div class="well col-xs-8 col-xs-offset-2">
  <% if @activity.member %>
    <ul class="listing">
      <div class="row center">
        <div class="col-md-4 col-md-offset-4">
          <li><h2>Created by:</h2></li>
          <li><h2><%= link_to gravatar_for(@activity.member), member_path(@activity.member)
          %></h2></li>
          <li class="member-title"><h2>
            <%= link_to @activity.member.username, member_path(@activity.member)  %></h2>
          </li>
        </div>
      </div>
    </ul>
    <% end %>



  <hr>
  <h3><%= simple_format(@activity.bio) %></h3>
  <% if @activity.categories.any? %>
    <h3>My Activities: <%= render @activity.categories %></h3>
  <% end %>
  <div class="activity-actions">
      <% if logged_in? && (current_member == @activity.member || current_member.admin?) %>
          <%= link_to "Edit this activity", edit_activity_path(@activity), class: "btn btn-primary" %>
          <%= link_to "Delete this article", activity_path(@activity), method: :delete, data: { confirm: "Are you sure , you want to delete the activity?" }, class: "btn btn-danger" %>
      <% end %>
      <%= link_to "view all activites listing", activities_path, class: "btn btn-success" %>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name , category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

      <%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
       <div class="form-group">
         <div class="control-label col-sm-4">
            <%= f.label :name %><br>
        </div>
        <div class="col-sm-3">
         <%= f.text_field :name , class: "form-control", placeholder: "Category name", autofocus: true  %>
        </div>
      </div>

      
      <div class="form-group">
        <div class="col-sm-offset-4 col-sm-8">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
    [<%= link_to "Cancel request and return to the activites listing", activities_path %>]
  

app/views/categories/edit.html.erb
<h1 align="center">Edit Category name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<div class="panel panel-success">
  <div class="panel-heading">
    <div class="panel-title">
    <h3 align="center">Listing All Activities</h3>
    </div>
  </div>
</div>

<div align="center">
  <%= will_paginate %>
  <% @categories.each do |category| %>
    <ul class="listing">
      <div class="row">
        <div class"well col-md-4 col-md-offset-4">
          <li class="activity-location">
            <h1><%= link_to "#{category.name}", category_path(category) %></h1>
          </li>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create new Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h3 align="center"><%= "Category: " + @category.name %></h3>
  <div align="center">
    <% if logged_in? and current_member.admin? %>
      <div class="row">
        <span class="badge"><%= link_to "Edit Category name", edit_category_path(@category) %></span>
      </div>
    <% end %>
   <%= will_paginate  @category_activities%>
  </div>

<%= render 'activities/activity', obj: @category_activities  %>

<div align="center">
  <%= will_paginate @category_activities %>
</div>
  

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
    <div class='alert alert-<%="#{name}" %>'>
      <a href="#" class="close" data-dismiss="alert">×</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to " // GymBuddies //", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       <li><%= link_to "Activities", activities_path %></li>
        <li><%= link_to "View Gym Members", members_path %></li>
         <% if logged_in? %>
              <li><%= link_to "New Activity", new_activity_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Categories <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%=link_to "All Categories", categories_path %></li>
              <% Category.all.each do |category| %>
              <li><%= link_to "#{category.name}", category_path(category) %></li>
            <% end %>
            <% if logged_in? and current_member.admin? %>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Create New Category", new_category_path %></li>
            <% end %>
            </ul>
          </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
       <% if logged_in? %>
          <li><%= link_to "logout", logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "ADMIN" if current_member.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%=link_to "Edit Your Profile", edit_member_path(current_member) %></li>
              <li><%=link_to "View your profile", member_path(current_member) %></li>
            </ul>
          </li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gym Members | The easiest way to find Gym members in you area!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <script src="https://use.fontawesome.com/f40685afe6.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="description" content='The easiest way to find Gym members in you area! '>
  <meta name="author" content="Neil Patel">
</head>
<body>

<div class="border"></div>

<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>


<%= yield %>

<footer id="main_footer">
  <p class="copyright"> &copy; 2016 Neil Patel</p>
   <nav>
    <a href="http://twitter.com/neilp666" target="_blank"><i class="fa fa-twitter"></i></a>
    <a href="http://www.facebook.com/indianstartupshow" target="_blank"><i class="fa fa-facebook"></i></a>
    <a href="http://github.com/neilp666" target="_blank"><i class="fa fa-github"></i></a>
   </nav>
</footer>

<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/members/_form.html.erb
<%= render 'shared/errors', obj: @member %>


  <div class="row">
    <div class="col-xs-12">
      <%= form_for(@member, :html => {class: "form-horizontal", role: "form"}) do |f| %>
       <div class="form-group">
         <div class="control-label col-sm-4">
            <%= f.label :username%><br>
        </div>
        <div class="col-sm-3">
         <%= f.text_field :username, class: "form-control", placeholder: "Enter Your Username", autofocus: true  %>
        </div>
      </div>

        <div class="form-group">
         <div class="control-label col-sm-4">
            <%= f.label :email %>
         </div>
         <div class="col-sm-4">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
        </div>
      </div>


      <div class="form-group">
         <div class="control-label col-sm-4">
            <%= f.label :password %>
         </div>
         <div class="col-sm-4">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter Password" %>
        </div>
      </div>


      <div class="form-group">
        <div class="col-sm-offset-4 col-sm-8">
          <%= f.submit(@member.new_record? ? "Sign up" : "Update account", class: 'btn btn-primary btn-lg') %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
    [<%= link_to "Cancel request and return to the activites listing", activities_path %>]
    </div>
  </div>
</div>

app/views/members/edit.html.erb
<div class="panel panel-success">
  <div class="panel-heading">
    <div class="panel-title">
    <h3 align="center">Edit Your Account </h3>
    </div>
  </div>
</div>
 <%= render 'form' %>

app/views/members/index.html.erb
<div class="panel panel-success">
  <div class="panel-heading">
    <div class="panel-title">
    <h3 align="center">All Gym Members</h3>
    </div>
  </div>
</div>

  <div align="center">
  <%= will_paginate %>
  <% @members.each do |member| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(member), member_path(member) %></li>
          <li class="member-title">
            <%= link_to member.username, member_path(member) %>
          </li>

        
          <% if logged_in? and current_member.admin? %>
            <li><%= link_to "Delete this gym member", member_path(member), method: :delete, data: { confirm: "Are you sure you want to 
              delete the user and all their activities"} %></li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
  </div>

app/views/members/new.html.erb
<div class="panel panel-success">
  <div class="panel-heading">
    <div class="panel-title">
    <h3 align="center">Signup for Gym Buddies</h3>
    </div>
  </div>
</div>
 <%= render 'form' %>

app/views/members/show.html.erb
<div class="panel panel-success">
  <div class="panel-heading">
    <div class="panel-title">
    <h3 align="center">Welcome to <%= @member.username %>'s page</h3>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @member, size: 150 %>
  </div>
</div>

<div class="center">
  <%= will_paginate @member_activities %>
</div>
<%= render 'activities/activity', obj: @member_activities %>

<div class="center">
  <%= will_paginate @member_activities %>
</div>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1><i class="fa fa-star-o"></i> Gym Buddies</h1>
   <h2>The easiest way to find Gym members in you area!</h2>
      <%= link_to "Get Started Today", signup_path, class: "btn btn-danger btn-lg btn-xlarge" %>
</div>

app/views/shared/_errors.html.erb
  <% if obj.errors.any? %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(obj.errors.count, "error") %>
              Prohibited this article from being saved
            </h2>
            <div class="panel-body">
              <ul>
                <% obj.errors.full_messages.each do |msg| %>
                 <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
  <% end %>